### ISSUE TITLE
can't clone with modman

### ISSUE THREAD

**Issue by arosenhagen** [aschroder/Magento-Speed-Test-Extension#1]
extension doesn't show up in admin when deploying with modman (symlinks).
copying the files to the appropriate location works.

**Comment by aschroder** [comment]
What platform are you on? Does it create symlinks when you deploy it (in the wrong place) - or none at all?

**Comment by arosenhagen** [comment]
using ubuntu with nginx. symlinks are created - everything seems fine - it just doesn't show up. same issue with other magento extensions, but some work.

**Comment by arosenhagen** [comment]
worked it out with your extension (seems to be a permission related problem on our side).
